# Generated by Django 4.0.4 on 2022-06-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_counter_user_isverified_alter_user_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isVerified',
        ),
    ]
