# Generated by Django 4.0.4 on 2022-06-29 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_degree', models.CharField(max_length=100)),
                ('doctor_speciality', models.CharField(max_length=100)),
                ('doctor_start_time', models.CharField(max_length=100)),
                ('doctor_end_time', models.CharField(max_length=100)),
                ('doctor_fees', models.CharField(max_length=100)),
                ('doctor_pic', models.ImageField(upload_to='')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
