# Generated by Django 4.0.4 on 2022-06-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_doctor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='doctor_fees',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
