# Generated by Django 4.0.4 on 2022-06-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_doctor_profile_doctor_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_profile',
            name='doctor_pic',
        ),
    ]
