# Generated by Django 4.0.4 on 2022-07-06 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_appoiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoiment',
            name='discrpiton',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appoiment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
