# Generated by Django 4.0.4 on 2022-07-06 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_appoiment_discrpiton_alter_appoiment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoiment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appoiment',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
