# Generated by Django 4.0.4 on 2022-07-06 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_appoiment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoiment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
