# Generated by Django 4.0.4 on 2022-07-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_appoiment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoiment',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
