# Generated by Django 4.0.4 on 2022-07-10 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_appoiment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancelappointmentaptient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_issue', models.CharField(max_length=100)),
                ('appoiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appoiment')),
            ],
        ),
    ]
