# Generated by Django 4.0.4 on 2022-07-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_cancelappointmentaptient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoiment',
            new_name='Appointment',
        ),
        migrations.RenameField(
            model_name='cancelappointmentaptient',
            old_name='appoiment',
            new_name='appointment',
        ),
    ]
