# Generated by Django 4.0.4 on 2022-07-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_appoiment_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelappointmentaptient',
            old_name='appointment',
            new_name='appointments',
        ),
    ]
