# Generated by Django 4.0.4 on 2022-07-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_appointment_cancelappointmentaptient_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorappointmentaptient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_issue', models.CharField(max_length=100)),
                ('appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment')),
            ],
        ),
    ]
